# AI-powered data-driven applications using pgvector, LangChain and LLMs

## Enviroment Setup

In [1]:
# Install dependencies.
!pip install asyncio==3.4.3 asyncpg==0.27.0 cloud-sql-python-connector["asyncpg"]==1.2.3
!pip install numpy==1.26.4 pandas
!pip install pgvector==0.1.8
!pip install langchain langchain_google_vertexai transformers
!pip install -U langchain-google-vertexai langchain-community
!pip install google-cloud-aiplatform
!pip install shapely
!pip install google-cloud-aiplatform[langchain,reasoningengine]
!pip install langchain-text-splitters
!pip install pydantic>=2.0

Collecting asyncio==3.4.3
  Downloading asyncio-3.4.3-py3-none-any.whl.metadata (1.7 kB)
Collecting asyncpg==0.27.0
  Downloading asyncpg-0.27.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl.metadata (4.7 kB)
Collecting cloud-sql-python-connector==1.2.3 (from cloud-sql-python-connector[asyncpg]==1.2.3)
  Downloading cloud_sql_python_connector-1.2.3-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (3.13.3)
Requirement already satisfied: cryptography>=38.0.3 in /opt/conda/lib/python3.10/site-packages (from cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (46.0.3)
Requirement already satisfied: Requests in /opt/conda/lib/python3.10/site-packages (from cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (2.32.5)
Requirement already satisfied: google-auth in /opt/conda/lib/python3.10/site-packages (from cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (2.47.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from cryptography>=38.0.3->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (2.0.0)
Requirement already satisfied: typing-extensions>=4.13.2 in /opt/conda/lib/python3.10/site-packages (from cryptography>=38.0.3->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (4.15.0)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.10/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (2.22)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (1.22.0)
Requirement already satisfied: idna>=2.0 in /opt/conda/lib/python3.10/site-packages (from yarl<2.0,>=1.17.0->aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (3.11)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.10/site-packages (from google-auth->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.10/site-packages (from google-auth->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (4.9.1)
Requirement already satisfied: pyasn1>=0.1.3 in /opt/conda/lib/python3.10/site-packages (from rsa<5,>=3.1.4->google-auth->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (0.6.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from Requests->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from Requests->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from Requests->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (2026.1.4)
Downloading asyncio-3.4.3-py3-none-any.whl (101 kB)
Downloading asyncpg-0.27.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 42.3 MB/s  0:00:00
Downloading cloud_sql_python_connector-1.2.3-py2.py3-none-any.whl (35 kB)
Installing collected packages: asyncio, asyncpg, cloud-sql-python-connector
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [cloud-sql-python-connector]
Successfully installed asyncio-3.4.3 asyncpg-0.27.0 cloud-sql-python-connector-1.2.3
Collecting numpy==1.26.4
  Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.10/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 80.5 MB/s  0:00:006m0:00:01
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.6
    Uninstalling numpy-2.2.6:
      Successfully uninstalled numpy-2.2.6
Successfully installed numpy-1.26.4
Collecting pgvector==0.1.8
  Downloading pgvector-0.1.8-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from pgvector==0.1.8) (1.26.4)
Downloading pgvector-0.1.8-py2.py3-none-any.whl (7.6 kB)
Installing collected packages: pgvector
Successfully installed pgvector-0.1.8
Collecting langchain
  Downloading langchain-1.2.6-py3-none-any.whl.metadata (4.9 kB)
Collecting langchain_google_vertexai
  Downloading langchain_google_vertexai-3.2.1-py3-none-any.whl.metadata (3.2 kB)
Collecting transformers
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
Collecting langchain-core<2.0.0,>=1.2.7 (from langchain)
  Downloading langchain_core-1.2.7-py3-none-any.whl.metadata (3.7 kB)
Collecting langgraph<1.1.0,>=1.0.2 (from langchain)
  Downloading langgraph-1.0.6-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /opt/conda/lib/python3.10/site-packages (from langchain) (2.12.5)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /opt/conda/lib/python3.10/site-packages (from langchain-core<2.0.0,>=1.2.7->langchain) (1.33)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain-core<2.0.0,>=1.2.7->langchain)
  Downloading langsmith-0.6.4-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /opt/conda/lib/python3.10/site-packages (from langchain-core<2.0.0,>=1.2.7->langchain) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /opt/conda/lib/python3.10/site-packages (from langchain-core<2.0.0,>=1.2.7->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /opt/conda/lib/python3.10/site-packages (from langchain-core<2.0.0,>=1.2.7->langchain) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /opt/conda/lib/python3.10/site-packages (from langchain-core<2.0.0,>=1.2.7->langchain) (4.15.0)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core<2.0.0,>=1.2.7->langchain)
  Downloading uuid_utils-0.13.0-cp39-abi3-manylinux_2_24_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: jsonpointer>=1.9 in /opt/conda/lib/python3.10/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.7->langchain) (3.0.0)
Collecting langgraph-checkpoint<5.0.0,>=2.1.0 (from langgraph<1.1.0,>=1.0.2->langchain)
  Downloading langgraph_checkpoint-4.0.0-py3-none-any.whl.metadata (4.9 kB)
Collecting langgraph-prebuilt<1.1.0,>=1.0.2 (from langgraph<1.1.0,>=1.0.2->langchain)
  Downloading langgraph_prebuilt-1.0.6-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.4.0,>=0.3.0 (from langgraph<1.1.0,>=1.0.2->langchain)
  Downloading langgraph_sdk-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting xxhash>=3.5.0 (from langgraph<1.1.0,>=1.0.2->langchain)
  Downloading xxhash-3.6.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain)
  Downloading ormsgpack-1.12.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: httpx>=0.25.2 in /opt/conda/lib/python3.10/site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Collecting orjson>=3.10.1 (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain)
  Downloading orjson-3.11.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /opt/conda/lib/python3.10/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in /opt/conda/lib/python3.10/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain) (0.25.0)
Requirement already satisfied: anyio in /opt/conda/lib/python3.10/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (4.12.1)
Requirement already satisfied: certifi in /opt/conda/lib/python3.10/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /opt/conda/lib/python3.10/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: idna in /opt/conda/lib/python3.10/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in /opt/conda/lib/python3.10/site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /opt/conda/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/conda/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Collecting bottleneck<2.0.0,>=1.4.0 (from langchain_google_vertexai)
  Downloading bottleneck-1.6.0-cp310-cp310-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (8.2 kB)
Requirement already satisfied: google-cloud-aiplatform<2.0.0,>=1.97.0 in /opt/conda/lib/python3.10/site-packages (from langchain_google_vertexai) (1.133.0)
Requirement already satisfied: google-cloud-storage<4.0.0,>=2.18.0 in /opt/conda/lib/python3.10/site-packages (from langchain_google_vertexai) (3.8.0)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain_google_vertexai)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Collecting numexpr<3.0.0,>=2.8.6 (from langchain_google_vertexai)
  Downloading numexpr-2.14.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)
Requirement already satisfied: pyarrow<23.0.0,>=19.0.1 in /opt/conda/lib/python3.10/site-packages (from langchain_google_vertexai) (22.0.0)
Collecting validators<1.0.0,>=0.22.0 (from langchain_google_vertexai)
  Downloading validators-0.35.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from bottleneck<2.0.0,>=1.4.0->langchain_google_vertexai) (1.26.4)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1 in /opt/conda/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (2.29.0)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /opt/conda/lib/python3.10/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (2.47.0)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /opt/conda/lib/python3.10/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (1.27.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2 in /opt/conda/lib/python3.10/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (6.33.4)
Requirement already satisfied: google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0 in /opt/conda/lib/python3.10/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (3.40.0)
Requirement already satisfied: google-cloud-resource-manager<3.0.0,>=1.3.3 in /opt/conda/lib/python3.10/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (1.15.0)
Requirement already satisfied: google-genai<2.0.0,>=1.37.0 in /opt/conda/lib/python3.10/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (1.57.0)
Requirement already satisfied: docstring_parser<1 in /opt/conda/lib/python3.10/site-packages (from google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (0.17.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /opt/conda/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (1.72.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /opt/conda/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (1.76.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /opt/conda/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (1.76.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.10/site-packages (from google-auth<3.0.0,>=2.47.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.10/site-packages (from google-auth<3.0.0,>=2.47.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (4.9.1)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (2.8.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (2.9.0.post0)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.14.0 in /opt/conda/lib/python3.10/site-packages (from google-cloud-resource-manager<3.0.0,>=1.3.3->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (0.14.3)
Requirement already satisfied: google-crc32c<2.0.0,>=1.1.3 in /opt/conda/lib/python3.10/site-packages (from google-cloud-storage<4.0.0,>=2.18.0->langchain_google_vertexai) (1.8.0)
Requirement already satisfied: websockets<15.1.0,>=13.0.0 in /opt/conda/lib/python3.10/site-packages (from google-genai<2.0.0,>=1.37.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (15.0.1)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/conda/lib/python3.10/site-packages (from google-genai<2.0.0,>=1.37.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (1.9.0)
Requirement already satisfied: sniffio in /opt/conda/lib/python3.10/site-packages (from google-genai<2.0.0,>=1.37.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (1.3.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in /opt/conda/lib/python3.10/site-packages (from anyio->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (1.3.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain) (2.6.3)
Requirement already satisfied: pyasn1>=0.1.3 in /opt/conda/lib/python3.10/site-packages (from rsa<5,>=3.1.4->google-auth<3.0.0,>=2.47.0->google-cloud-aiplatform<2.0.0,>=1.97.0->langchain_google_vertexai) (0.6.1)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from transformers) (3.20.3)
Collecting huggingface-hub<1.0,>=0.34.0 (from transformers)
  Downloading huggingface_hub-0.36.0-py3-none-any.whl.metadata (14 kB)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2026.1.15-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting safetensors>=0.4.3 (from transformers)
  Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2026.1.0)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.34.0->transformers)

In [2]:
# Automatically restart kernel after installation so that your environment can access the new packages.
import IPython

app = IPython.Application.instance()
app.kernel.do_shutdown(True)

{'status': 'ok', 'restart': True}

## install packages

In [1]:
import os
import pandas as pd
import vertexai
from vertexai.language_models import TextEmbeddingModel
from vertexai.generative_models import GenerativeModel
from IPython.display import display, Markdown

from langchain_google_vertexai import VertexAIEmbeddings
import vertexai

project_id = "qwiklabs-gcp-02-c72a978ae543"
database_password = "cymbal@123!"
region =  "us-central1"
instance_name = "retail-ins"
database_name = "retail"
database_user = "retail-admin"

# Initialize Vertex AI SDK
vertexai.init(project=project_id, location=region)

/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform_v1beta1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform_v1beta1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform_v1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/cloud/aiplatform/models.py:52: FutureWarning: Support for google-cloud-storage < 3.0.0 will be removed in a future version of google-cloud-aiplatform. Please upgrade to google-cloud-storage >= 3.0.0.
  from google.cloud.aiplatform.utils import gcs_utils
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1.schema.predict.instance_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1.schema.predict.instance_v1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1.schema.predict.params_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1.schema.predict.params_v1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1.schema.predict.prediction_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1.schema.predict.prediction_v1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1.schema.trainingjob.definition_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1.schema.trainingjob.definition_v1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1beta1.schema.predict.instance_v1beta1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1beta1.schema.predict.instance_v1beta1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1beta1.schema.predict.params_v1beta1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1beta1.schema.predict.params_v1beta1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1beta1.schema.predict.prediction_v1beta1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1beta1.schema.predict.prediction_v1beta1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1beta1.schema.trainingjob.definition_v1beta1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1beta1.schema.trainingjob.definition_v1beta1 past that date.
  warnings.warn(message, FutureWarning)
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

## Create a Cloud SQL Instance and PostgreSQL database.

In [2]:
#@markdown Create and setup a Cloud SQL PostgreSQL instance, if not done already.
database_version = !gcloud sql instances describe {instance_name} --format="value(databaseVersion)"
if database_version[0].startswith("POSTGRES"):
  print("Found an existing Postgres Cloud SQL Instance!")
else:
  print("Creating new Cloud SQL instance...")
  !gcloud sql instances create {instance_name} --database-version=POSTGRES_15 \
  --region={region} --cpu=1 --memory=4GB --root-password={database_password}

# Create the database, if it does not exist.
out = !gcloud sql databases list --instance={instance_name} --filter="NAME:{database_name}" --format="value(NAME)"
if ''.join(out) == database_name:
  print("Database %s already exists, skipping creation." % database_name)
else:
  !gcloud sql databases create {database_name} --instance={instance_name}

# Create the database user for accessing the database.
!gcloud sql users create {database_user} \
--instance={instance_name} \
--password={database_password}

Creating new Cloud SQL instance...
Creating Cloud SQL instance for POSTGRES_15...done.
Created [https://sqladmin.googleapis.com/sql/v1beta4/projects/qwiklabs-gcp-02-c72a978ae543/instances/retail-ins].
NAME        DATABASE_VERSION  LOCATION       TIER              PRIMARY_ADDRESS  PRIVATE_ADDRESS  STATUS
retail-ins  POSTGRES_15       us-central1-c  db-custom-1-4096  35.222.113.71    -                RUNNABLE
Creating Cloud SQL database...done.
Created database [retail].
instance: retail-ins
name: retail
project: qwiklabs-gcp-02-c72a978ae543
Creating Cloud SQL user...done.
Created user [retail-admin].

In [ ]:
# @markdown Verify that you are able to connect to the database.

import asyncio
import asyncpg
from google.cloud.sql.connector import Connector


async def main():
    # get current running event loop to be used with Connector
    loop = asyncio.get_running_loop()
    # initialize Connector object as async context manager
    async with Connector(loop=loop) as connector:
        # create connection to Cloud SQL database
        conn: asyncpg.Connection = await connector.connect_async(
            f"{project_id}:{region}:{instance_name}",  # Cloud SQL instance connection name
            "asyncpg",
            user=f"{database_user}",
            password=f"{database_password}",
            db=f"{database_name}"
            # ... additional database driver args
        )

        # query Cloud SQL database
        results = await conn.fetch("SELECT version()")
        print(results[0]["version"])

        # close asyncpg connection
        await conn.close()


# Test connection with `asyncio`
await main()

/opt/conda/lib/python3.10/site-packages/google/cloud/sql/connector/__init__.py:23: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

PostgreSQL 15.15 on x86_64-pc-linux-gnu, compiled by Debian clang version 12.0.1, 64-bit

/opt/conda/lib/python3.10/site-packages/google/cloud/sql/connector/instance.py:330: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_after_utc.
  expiration = x509.not_valid_after

## Download and load the dataset in PostgreSQL

In [4]:
# Load dataset from a web URL and store it in a pandas dataframe.

import pandas as pd
import os

DATASET_URL = "https://github.com/GoogleCloudPlatform/python-docs-samples/raw/main/cloud-sql/postgres/pgvector/data/retail_toy_dataset.csv"
df = pd.read_csv(DATASET_URL)
df = df.loc[:, ["product_id", "product_name", "description", "list_price"]]
df = df.dropna()
df.head(10)

,product_id,product_name,description,list_price
0,7e8697b5b7cdb5a40daf54caf1435cd5,"Koplow Games Set of 2 D12 12-Sided Rock, Paper...","Rock, paper, scissors is a great way to resolv...",3.56
1,7de8b315b3cb91f3680eb5b88a20dcee,"12""-20"" Schwinn Training Wheels",Turn any small bicycle into an instrument for ...,28.17
2,fb9535c103d7d717f0414b2b111cfaaa,Bicycle Pinochle Jumbo Index Playing Cards - 1...,Purchase includes 1 blue deck and 1 red deck. ...,6.49
3,c73ea622b3be6a3ffa3b0b5490e4929e,Step2 Woodland Adventure Playhouse & Slide,The Step2 Woodland Climber Adventure Playhouse...,499.99
4,dec7bd1f983887650715c6fafaa5b593,Step2 Naturally Playful Welcome Home Playhouse...,Children can play and explore in the Step2 Nat...,600.00
5,74a695e3675efc2aad11ed73c46db29b,Slip N Slide Triple Racer with Slide Boogies,Triple Racer Slip and Slide with Boogie Boards...,37.21
6,3eae5293b56c25f63b47cb8a89fb4813,Hydro Tools Digital Pool/Spa Thermometer,The solar-powered Swimline Floating Digital Th...,15.92
7,ed85bf829a36c67042503ffd9b6ab475,Full Bucket Swing With Coated Chain Toddler Sw...,Safe Kids&Children Full Bucket Swing With Coa...,102.26
8,55820fa53f0583cb637d5cb2b051d78c,Banzai Water Park Splash Zone,Dive into fun in your own backyard with the B...,397.82
9,0e26a9e92e4036bfaa68eb2040a8ec97,Polaris 39-310 5-Liter Zippered Super Bag for ...,Keep your pool water sparkling clean all seaso...,39.47

In [ ]:
# Save the Pandas dataframe in a PostgreSQL table.

import asyncio
import asyncpg
from google.cloud.sql.connector import Connector


async def main():
    loop = asyncio.get_running_loop()
    async with Connector(loop=loop) as connector:
        # Create connection to Cloud SQL database
        conn: asyncpg.Connection = await connector.connect_async(
            f"{project_id}:{region}:{instance_name}",  # Cloud SQL instance connection name
            "asyncpg", 
            user=f"{database_user}",
            password=f"{database_password}",
            db=f"{database_name}",
        )

        await conn.execute("DROP TABLE IF EXISTS products CASCADE")
        # Create the `products` table.
        await conn.execute(
            """CREATE TABLE products(
                                product_id VARCHAR(1024) PRIMARY KEY,
                                product_name TEXT,
                                description TEXT,
                                list_price NUMERIC)"""
        )

        # Copy the dataframe to the `products` table.
        tuples = list(df.itertuples(index=False))
        await conn.copy_records_to_table(
            "products", records=tuples, columns=list(df), timeout=10
        )
        await conn.close()


# Run the SQL commands now.
await main()

/opt/conda/lib/python3.10/site-packages/google/cloud/sql/connector/instance.py:330: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_after_utc.
  expiration = x509.not_valid_after

## Generate vector embeddings using a Text Embedding model

In [6]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain.schema import Document

from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    separators=[".", "\n"],
    chunk_size=500,
    chunk_overlap=0,
    length_function=len,
)

max_documents = 47  # Reduced limit to further control API usage
documents = []

# Create Document objects with product_id as metadata
for index, row in df.iterrows():
    product_id = row["product_id"]
    desc = row["description"]
    documents.append(Document(page_content=desc, metadata={"product_id": product_id}))

# Use the text splitter on a subset of documents (e.g., 40-50)
chunked = []
docs = text_splitter.split_documents(documents[40:max_documents])

# Collect split content along with product_id
for doc in docs:
    chunked.append({"product_id": doc.metadata["product_id"], "content": doc.page_content})

In [7]:
from langchain_google_vertexai import VertexAIEmbeddings
from google.cloud import aiplatform
import time

embeddings_service = VertexAIEmbeddings(model_name="text-embedding-005")

# Helper function to retry failed API requests with exponential backoff.
def retry_with_backoff(func, *args, retry_delay=10, backoff_factor=2.5, **kwargs):  # Increased delay and backoff factor
    max_attempts = 10
    retries = 0
    for i in range(max_attempts):
        try:
            return func(*args, **kwargs)
        except Exception as e:
            print(f"error: {e}")
            retries += 1
            wait = retry_delay * (backoff_factor**retries)
            print(f"Retry after waiting for {wait} seconds...")
            time.sleep(wait)

# Reduced batch size for API calls to manage quota limits
batch_size = 3
for i in range(0, len(chunked), batch_size):
    request = [x["content"] for x in chunked[i : i + batch_size]]
    response = retry_with_backoff(embeddings_service.embed_documents, request)
    # Store the retrieved vector embeddings for each chunk back.
    for x, e in zip(chunked[i : i + batch_size], response):
        x["embedding"] = e

# Store the generated embeddings in a pandas dataframe.
product_embeddings = pd.DataFrame(chunked)
product_embeddings.head()

/opt/conda/lib/python3.10/site-packages/vertexai/_model_garden/_model_garden_models.py:278: UserWarning: This feature is deprecated as of June 24, 2025 and will be removed on June 24, 2026. For details, see https://cloud.google.com/vertex-ai/generative-ai/docs/deprecations/genai-vertexai-sdk.
  warning_logs.show_deprecation_warning()

,product_id,content,embedding
0,8a6d71be41e01b284294ec488508b414,All of our productsWalmartply with internation...,"[0.04086191579699516, -0.020511694252490997, -..."
1,8a6d71be41e01b284294ec488508b414,. Holds Up to 6 Decks Fun for the whole family...,"[0.01160380244255066, -0.021363208070397377, -..."
2,9648838f5badebb9fc0b07f89cc29394,Better circulate water through your pool with ...,"[-0.005303527694195509, 0.017071831971406937, ..."
3,9648838f5badebb9fc0b07f89cc29394,".25-inch fitting (11070), 2 strainer grids (11...","[-0.01586345210671425, 0.017979448661208153, -..."
4,9648838f5badebb9fc0b07f89cc29394,. Circulate water through your pool with the h...,"[0.0184821505099535, 0.01372526679188013, 0.00..."

## Use pgvector to store the generated embeddings within PostgreSQL

In [ ]:
# Store the generated vector embeddings in a PostgreSQL table.

import asyncio
import asyncpg
from google.cloud.sql.connector import Connector
import numpy as np
from pgvector.asyncpg import register_vector


async def main():
    loop = asyncio.get_running_loop()
    async with Connector(loop=loop) as connector:
        # Create connection to Cloud SQL database.
        conn: asyncpg.Connection = await connector.connect_async(
            f"{project_id}:{region}:{instance_name}",  # Cloud SQL instance connection name
            "asyncpg",
            user=f"{database_user}",
            password=f"{database_password}",
            db=f"{database_name}",
        )

        await conn.execute("CREATE EXTENSION IF NOT EXISTS vector")
        await register_vector(conn)

        await conn.execute("DROP TABLE IF EXISTS product_embeddings")
        # Create the `product_embeddings` table to store vector embeddings.
        await conn.execute(
            """CREATE TABLE product_embeddings(
                                product_id VARCHAR(1024) NOT NULL REFERENCES products(product_id),
                                content TEXT,
                                embedding vector(768))"""
        )

        # Store all the generated embeddings back into the database.
        for index, row in product_embeddings.iterrows():
            await conn.execute(
                "INSERT INTO product_embeddings (product_id, content, embedding) VALUES ($1, $2, $3)",
                row["product_id"],
                row["content"],
                np.array(row["embedding"]),
            )

        await conn.close()


# Run the SQL commands now.
await main()  # type: ignore

/opt/conda/lib/python3.10/site-packages/google/cloud/sql/connector/instance.py:330: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_after_utc.
  expiration = x509.not_valid_after

## Finding similar toy products using pgvector cosine search operator

In [ ]:
# @markdown Enter a short description of the toy to search for within a specified price range:
toy = "playing card games" 
min_price = 25  
max_price = 100  

# Quick input validations.
assert toy, "⚠️ Please input a valid input search text"

from langchain_google_vertexai import VertexAIEmbeddings
from google.cloud import aiplatform

aiplatform.init(project=f"{project_id}", location=f"{region}")

embeddings_service = VertexAIEmbeddings(model_name="text-embedding-005")
qe = embeddings_service.embed_query(toy)
from pgvector.asyncpg import register_vector
import asyncio
import asyncpg
from google.cloud.sql.connector import Connector

matches = []


async def main():
    loop = asyncio.get_running_loop()
    async with Connector(loop=loop) as connector:
        # Create connection to Cloud SQL database.
        conn: asyncpg.Connection = await connector.connect_async(
            f"{project_id}:{region}:{instance_name}",  
            "asyncpg",
            user=f"{database_user}",
            password=f"{database_password}",
            db=f"{database_name}",
        )

        await register_vector(conn)
        similarity_threshold = 0.1
        num_matches = 50

        # Find similar products to the query using the cosine similarity search
        # Over all vector embeddings. This new feature is provided by `pgvector`.
        results = await conn.fetch(
            """
                            WITH vector_matches AS (
                            SELECT product_id, 1 - (embedding <=> $1) AS similarity
                            FROM product_embeddings
                            WHERE 1 - (embedding <=> $1) > $2
                            ORDER BY similarity DESC
                            LIMIT $3
                            )
                            SELECT product_name, list_price, description FROM products
                            WHERE product_id IN (SELECT product_id FROM vector_matches)
                            AND list_price >= $4 AND list_price <= $5
                            """,
            qe,
            similarity_threshold,
            num_matches,
            min_price,
            max_price,
        )

        if len(results) == 0:
            raise Exception("Did not find any results. Adjust the query parameters.")

        for r in results:
            # Collect the description for all the matched similar toy products.
            matches.append(
                {
                    "product_name": r["product_name"],
                    "description": r["description"],
                    "list_price": round(r["list_price"], 2),
                }
            )

        await conn.close()


# Run the SQL commands now.
await main()  

# Show the results for similar products that matched the user query.
matches = pd.DataFrame(matches)
matches.head(5)

/opt/conda/lib/python3.10/site-packages/vertexai/_model_garden/_model_garden_models.py:278: UserWarning: This feature is deprecated as of June 24, 2025 and will be removed on June 24, 2026. For details, see https://cloud.google.com/vertex-ai/generative-ai/docs/deprecations/genai-vertexai-sdk.
  warning_logs.show_deprecation_warning()

,product_name,description,list_price
0,Intex 26004E Above Ground Swimming Pool Inlet ...,Better circulate water through your pool with ...,39.99
1,KARMAS PRODUCT Heavy Duty Glider Swing for Kid...,KARMAS PRODUCT Heavy Duty Glider Swing for Kid...,49.99
2,Melissa & Doug Jumbo ABC-123 Rug (58 x 79 inch...,Kids will have jumbo amounts of fun exploring ...,54.99
3,Champion Sports Tournament Series Horseshoe Set,The Champion Sports Deluxe Horseshoe Tournamen...,61.06

## LLMs and LangChain

### Building an AI-curated contextual hybrid search

In [ ]:
# @markdown Enter the user search query in a simple English text. The price filters are shown separately here for demo purposes. These filters may represent additional input from your frontend application.

user_query = "Do you have a beach toy set that teaches numbers and letters to kids?"  
min_price = 20  
max_price = 100  

# Quick input validations.
assert user_query, "⚠️ Please input a valid input search text"

In [11]:
qe = embeddings_service.embed_query(user_query)

In [ ]:
from pgvector.asyncpg import register_vector
import asyncio
import asyncpg
from google.cloud.sql.connector import Connector

matches = []


async def main():
    loop = asyncio.get_running_loop()
    async with Connector(loop=loop) as connector:
        # Create connection to Cloud SQL database.
        conn: asyncpg.Connection = await connector.connect_async(
            f"{project_id}:{region}:{instance_name}",  
            "asyncpg",
            user=f"{database_user}",
            password=f"{database_password}",
            db=f"{database_name}",
        )

        await register_vector(conn)
        similarity_threshold = 0.5
        num_matches = 10

        # Find similar products to the query using cosine similarity search
        # over all vector embeddings. This new feature is provided by `pgvector`.
        results = await conn.fetch(
            """
                            WITH vector_matches AS (
                            SELECT product_id, 1 - (embedding <=> $1) AS similarity
                            FROM product_embeddings
                            WHERE 1 - (embedding <=> $1) > $2
                            ORDER BY similarity DESC
                            LIMIT $3
                            )
                            SELECT product_name, list_price, description FROM products
                            WHERE product_id IN (SELECT product_id FROM vector_matches)
                            AND list_price >= $4 AND list_price <= $5
                            """,
            qe,
            similarity_threshold,
            num_matches,
            min_price,
            max_price,
        )
        if len(results) == 0:
            raise Exception("Did not find any results. Adjust the query parameters.")

        for r in results:
            # Collect the description for all the matched similar toy products.
            matches.append(
                f"""The name of the toy is {r["product_name"]}.
                        The price of the toy is ${round(r["list_price"], 2)}.
                        Its description is below:
                        {r["description"]}."""
            )
        await conn.close()


# Run the SQL commands now.
await main()  

# Show the results for similar products that matched the user query.
matches

/opt/conda/lib/python3.10/site-packages/google/cloud/sql/connector/instance.py:330: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_after_utc.
  expiration = x509.not_valid_after

['The name of the toy is Champion Sports Tournament Series Horseshoe Set.\n                        The price of the toy is $61.06.\n                        Its description is below:\n                        The Champion Sports Deluxe Horseshoe Tournament Set features everything you need to set up a horseshoe tournament, including a set of rules to ensure games stay on track. The tough steel horseshoes are plated with chrome and brass for an attractive shine and extra durability, and the set includes two rugged chrome-plated steel stakes to take aim at. The horseshoe set comes with a carrying bag made from strong 1680 denier nylon fabric that can endure toting the sturdy heavy metal pieces around with ease. Two bronze powder coated steel horseshoes Two silver powder coated steel horseshoes Two silver powder coated solid steel stakes One durable weather-resistant 1680 Denier nylon carry bag with YKK zipper and embroidered logo Two bronze powder coated steel horseshoesTwo silver powder coated steel horseshoesTwo silver powder coated solid steel stakesOne durable weather-resistant 1680 Denier nylon carry bag with YKK zipper and embroidered logo.',
 'The name of the toy is KARMAS PRODUCT Heavy Duty Glider Swing for Kids Fun Swing Seat.\n                        The price of the toy is $49.99.\n                        Its description is below:\n                        KARMAS PRODUCT Heavy Duty Glider Swing for Kids Fun Swing Seat; Heavy Duty Glider Swing,play more fun! Use highly durable plastic ,very strong. Features footrests and handholds for added comfort and security Push with your feet; pull with your hands to get this glider swing flying Meets US ASTM safety standards Suitable for children 3 years up,Max weight is 55 pounds(25KG) Use highly durable plastic ,very strong.Features footrests and handholds for added comfort and securityPush with your feet; pull with your hands to get this glider swing flyingMeets US ASTM safety standardsSuitable for children 3 years up,Max weight is 55 pounds(25KG).',
 'The name of the toy is 11.5" Playing Cards Plastic Dealer Shoe, Clear & Black, Holds Up to 6 Decks By CHH.\n                        The price of the toy is $24.89.\n                        Its description is below:\n                         All of our productsWalmartply with international quality standards and are greatly appreciated in a variety of different markets throughout the world. 2710LC Features: -Material: plastic. -Holds up to 6 decks of cards. Game: -Poker. Accessory Type: -Card Dispensers. For Travel: -Yes. Dimensions: Overall Product Weight: -2.5 Pounds. If you are interested in any of our products or would like to discuss a custom order, please feel free to contact us. Holds Up to 6 Decks Fun for the whole family! Smooth Rolling Action Heavy Plastic Holds Up to 6 DecksFun for the whole family!Smooth Rolling ActionHeavy Plastic.',
 'The name of the toy is Melissa & Doug Jumbo ABC-123 Rug (58 x 79 inches – 36 Game Cards.\n                        The price of the toy is $54.99.\n                        Its description is below:\n                        Kids will have jumbo amounts of fun exploring and learning the alphabet, numbers, colors, and shapes on the Jumbo ABC-123 Rug! Theres more than 30 square feet of play space on the durable and soft rug to play matching games with the set of 36 double-sided game cards. There are whimsical pictures with each letter of the alphabet and numbers one through nine, and the border includes 12 shapes and shape names. Made from durable material that is incredibly soft to the touch for extra comfortable play, this multi-activity rug features a skid-proof backing and reinforced border binding. The rug measures approximately 58 inches x 79 inches. Melissa & Doug Jumbo ABC-123 Rug (58 x 79 inches – 36 Game Cards: Oversized activity rug with illustrated alphabet, numbers 1-9, shapes, and colors Includes 36 double-sided game cards Lots of room for multiple kids to play matching games Soft, durable material, skid-proof backing, and reinforced border binding Ages 3+; 4 10” x 6 7” (58 x 79 in./147 x 200 cm) Oversized activity rug with illustrated alphabet, numbers 1-9, shapes, and colorsIncludes 36 double-sided game cardsLots of room for multiple kids to play matching gamesSoft, durable material, skid-proof backing, and reinforced border bindingAges 3+; 4 10” x 6 7” (58 x 79 in./147 x 200 cm).']

In [ ]:
# Using LangChain for summarization and efficient context building.

from langchain.chains.summarize import load_summarize_chain
from langchain.docstore.document import Document
from langchain_google_vertexai import VertexAI
from langchain_core.prompts import PromptTemplate
from IPython.display import display, Markdown

llm = VertexAI(temperature=0.7)

map_prompt_template = """
            You will be given a detailed description of a toy product.
            This description is enclosed in triple backticks (```).
            Using this description only, extract the name of the toy,
            the price of the toy and its features.

            ```{text}```
            SUMMARY:
            """
map_prompt = PromptTemplate(template=map_prompt_template, input_variables=["text"])

combine_prompt_template = """
                You will be given a detailed description different toy products
                enclosed in triple backticks (```) and a question enclosed in
                double backticks(``).
                Select one toy that is most relevant to answer the question.
                Using that selected toy description, answer the following
                question in as much detail as possible.
                You should only use the information in the description.
                Your answer should include the name of the toy, the price of the toy
                and its features. Your answer should be less than 200 words.
                Your answer should be in Markdown in a numbered list format.


                Description:
                ```{text}```


                Question:
                ``{user_query}``


                Answer:
                """
combine_prompt = PromptTemplate(
    template=combine_prompt_template, input_variables=["text", "user_query"]
)

docs = [Document(page_content=t) for t in matches]
chain = load_summarize_chain(
    llm, chain_type="map_reduce", map_prompt=map_prompt, combine_prompt=combine_prompt
)
output = chain.invoke(
    {
        "input_documents": docs,
        "user_query": user_query,
    }
)


# Extract and display the output
answer = output.get('output_text', ' ')
display(Markdown(answer))

The most relevant toy to the question is the **Melissa & Doug Jumbo ABC-123 Rug**.

Here's why and the requested information:

1.  The Melissa & Doug Jumbo ABC-123 Rug is priced at \$54.99.
2.  It features an illustrated alphabet, numbers 1-9, shapes, and colors.
3.  It includes 36 double-sided game cards.
4.  The rug is made of soft, durable material and has a skid-proof backing and reinforced border binding.

### Adding AI-powered creative content generation

In [ ]:
# @markdown Describe your a new product in just a few words:

creative_prompt = "A bicycle with brand name 'Roadstar bike' for kids that comes with training wheels and helmet." 

# Quick input validations.
assert creative_prompt, "⚠️ Please input a valid input search text"

In [ ]:
from pgvector.asyncpg import register_vector
import asyncio
import asyncpg
from google.cloud.sql.connector import Connector

qe = embeddings_service.embed_query(creative_prompt)
qe_str = "[%s]" % (",".join([str(x) for x in qe]))
matches = []


async def main():
    loop = asyncio.get_running_loop()
    async with Connector(loop=loop) as connector:
        # Create connection to Cloud SQL database.
        conn: asyncpg.Connection = await connector.connect_async(
            f"{project_id}:{region}:{instance_name}",  
            "asyncpg",
            user=f"{database_user}",
            password=f"{database_password}",
            db=f"{database_name}",
        )

        await register_vector(conn)
        similarity_threshold = 0.5

        # Find similar products to the query using cosine similarity search
        # over all vector embeddings. This new feature is provided by `pgvector`.
        results = await conn.fetch(
            """
                            WITH vector_matches AS (
                            SELECT product_id, 1 - (embedding <=> $1) AS similarity
                            FROM product_embeddings
                            WHERE 1 - (embedding <=> $2) > $3
                            ORDER BY similarity DESC
                            LIMIT 1
                            )
                            SELECT description FROM products
                            WHERE product_id IN (SELECT product_id FROM vector_matches)
                            """,
            qe,
            qe,
            similarity_threshold,
        )

        for r in results:
            matches.append(r["description"])

        await conn.close()


# Run the SQL commands now.
await main()  

# Show the matched product description.
matches

/opt/conda/lib/python3.10/site-packages/google/cloud/sql/connector/instance.py:330: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_after_utc.
  expiration = x509.not_valid_after

['KARMAS PRODUCT Heavy Duty Glider Swing for Kids Fun Swing Seat; Heavy Duty Glider Swing,play more fun! Use highly durable plastic ,very strong. Features footrests and handholds for added comfort and security Push with your feet; pull with your hands to get this glider swing flying Meets US ASTM safety standards Suitable for children 3 years up,Max weight is 55 pounds(25KG) Use highly durable plastic ,very strong.Features footrests and handholds for added comfort and securityPush with your feet; pull with your hands to get this glider swing flyingMeets US ASTM safety standardsSuitable for children 3 years up,Max weight is 55 pounds(25KG)']

In [ ]:
from IPython.display import display, Markdown
from langchain_google_vertexai import VertexAI
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnableSequence

template = """
            You are given descriptions about some similar kind of toys in the context.
            This context is enclosed in triple backticks (```).
            Combine these descriptions and adapt them to match the specifications in
            the initial prompt. All the information from the initial prompt must
            be included. You are allowed to be as creative as possible,
            and describe the new toy in as much detail. Your answer should be
            less than 200 words.

            Context:
            ```{context}```

            Initial Prompt:
            {creative_prompt}
            Answer:
        """

prompt = PromptTemplate(
    template=template, input_variables=["context", "creative_prompt"]
)


# Define the LLM
llm = VertexAI(temperature=0.7)
# Example `matches` list

matches = [
    {"description": "This is a toy description 1."},
    {"description": "This is a toy description 2."},
    {},  # Missing `description`
    "Invalid item" 
]

# Construct the context by extracting valid descriptions
context = "\n".join(
    item["description"] for item in matches if isinstance(item, dict) and "description" in item
)

# Use RunnableSequence for chaining
llm_chain = RunnableSequence(prompt | llm)
# Invoke the chain
answer = llm_chain.invoke({
    "context": context,
    "creative_prompt": creative_prompt,
})

# Display the answer in Markdown format
display(Markdown(answer))

```This is a toy description 1. The 'Zoomster' balance bike helps toddlers develop coordination and balance before transitioning to a pedal bike. It features a lightweight frame, adjustable seat, and puncture-proof tires for safe and comfortable riding. Available in vibrant colors.

This is a toy description 2. The 'Trailblazer' kids' mountain bike is perfect for adventurous youngsters. It boasts front suspension, reliable brakes, and multiple gears for tackling varied terrain. Safety features include reflectors and a chain guard. Durable and built to last.```

Introducing the 'Roadstar Bike' – the perfect first bicycle for your child! This vibrant and sturdy bike comes equipped with removable training wheels, making it ideal for kids learning to ride. Safety is paramount, so each 'Roadstar Bike' includes a matching helmet. Inspired by balance bikes, the lightweight frame and adjustable seat ensure a comfortable fit. Built to last like a mountain bike, the 'Roadstar Bike' will provide years of fun and adventure. Get your little one rolling with confidence!